### ISSUE TITLE
TPM_ALG_KEYDHASH Template

### ISSUE THREAD

**Issue by stefvas** [kgoldman/ibmtss#4]
While implementing a Trusted Computing protocol with the TPM(SW TPM ibmtpm1661) , we 've encountered an error upon creating a KEYEDHASH key(reserved bits shall be set to zero),when using your template found in the file ObjectTemplates.c .The issue was resolved by adding to the attributes of the public key template TPA_OBJECT_RESERVED.
Kind regards ,
Stefanos Vasileiadis,
Alexandros Sampanis,
Ubitech Athens DST GROUP

**Comment by kgoldman** [comment]
Can you be more specific.

1. What were the steps to reproduce the error?  What command?  What software?
2. What was the error?
3. How did you fix it?

In the command line utilities, the attributes are first set to 0, and then attributes are added or removed.  The reserved fields should already be zero.  In addition, if the caller sets a reserved bit, TSS_TPMA_OBJECT_Unmarshalu should detect the error before the command is sent to the TPM.

**Comment by stefvas** [comment]
Hello and sorry for the delayed response, using the command line utilities i didnt encountered any errors while Creating a primary KEYED_HASH key however when i tried to integrate your template to my code i had an error ,reserved bits must be set to zero that was overcome by adding in the attributes of the key's public area   publicArea.objectAttributes.val &= ~TPMA_OBJECT_RESERVED.There may be an error elsewhere i will keep looking into it.
Kind regards Stefanos

________________________________

**Comment by kgoldman** [comment]
It sounds like you found a fix to your code.  The reserved bits must be 0.

I typically just set the publicArea.objectAttributes.val = 0 before I start adding attributes so the reserved bits will be zero.
