### ISSUE TITLE
Thread-safety is not as crazy as it might sound

### ISSUE THREAD

**Issue by nicowilliams** [kgoldman/ibmtss#5]
Suppose you're talking to multiple TPMs -- remote ones, probably.  Then reentrance and thread-safety seem useful.

The use-case I've in mind is doing something like password validation using remote TPMs -- remote because they could be a software TPM running on fast general-purpose hardware on a system built like an HSM.

**Comment by kgoldman** [comment]
Do you think there's an issue?  The only global variable I know of is the verbose flag for debugging.

**Comment by nicowilliams** [comment]
There's also `tssFirstCall`, used for self-initialization, where normally one would use a `pthread_once()`.  Apps can call `TSS_SetProperty()` via a `pthread_once()` to work around that.

The writable globals in library code seem to be `tssFirstCall`, `tssUtilsVerbose`, `tssVerbose`, and `tssVverbose`.  The last two are set when enabling tracing through `TSS_SetProperty()` -- those could maybe be made thread-locals.  I agree that mostly these are a non-issue.

**Comment by nicowilliams** [comment]
I've been thinking it'd be very nice to have a fast, networked HSM w/ a TPM 2.0 interface, to be accessed remotely for password validation, and in that case some clients might well be multi-threaded, thus the interest in thread safety.  Context [here](https://www.metzdowd.com/pipermail/cryptography/2023-January/038094.html).

**Comment by kgoldman** [comment]
What's a good design pattern for the verbose flags? The global is a hack, but I didn't want to pass them all down through every API.
The firstCall is probably historical (or for future use) now.  OpenSSL used to have a few calls that had to be done once per application, not once per thread.  That global is intentional.

**Comment by nicowilliams** [comment]
Options:

 - have a context object passed to every API function (ok)
 - have extra arguments passed to every API function (bad)
 - use globals (bad)
 - use thread-locals (ok for verbose flags, not so much for more call-specific extensions)

In general I prefer the context argument approach.  In a language like Haskell that would be a lot like saying "let's shove these things into a Reader monad".

A context argument would also let you stuff all sorts of extended diagnostics, traces, etc, into the context.

But I'd settle for thread-locals for this particular case.  There's not a lot of room for extending these APIs, so there is probably not that much reason for adding a context argument.
