### ISSUE TITLE
Fixing "Loaded objects (keys) disappear" by automatically doing ContextSave/ContextLoad

### ISSUE THREAD

**Issue by nicowilliams** [kgoldman/ibmtss#6]
One thing that is really convenient about the `tpm2-tools` is that they generally can consume / produce saved contexts in places where normally one would expect other items like public areas and so on.  This does mean that those utilities need to be able to execute more commands than their names imply, but this seems pretty normal.  This use of saved contexts means that "loaded objects disappear" doesn't happen as much.  Yes, "loaded objects disappear" could still happen when using a TPM directly while racing with other users of the same TPM because one has to keep flushing transient objects to make it all work, but racing like that should be rare.

**Comment by kgoldman** [comment]
Please take any discussion of the Intel TSS to their mailing list.  The IBM TSS and tools are designed to work without the application needing to deal with contexts.

The TPM device drivers have a resource manager.  They do the context save and load.  There should be no 'race'.  Some resource managers will even block the user space application from doing context save / load because of weird interactions with other processes and kernel use of the TPM.

In general, just go through the resource manager and it should all work just as if your application was the only TPM user.

**Comment by nicowilliams** [comment]
I think options to use saved contexts are a good feature to have.  I'm not proposing changes to the Intel tools, just mentioning one feature they have that I think would be useful in the IBM TPM utilities.

**Comment by kgoldman** [comment]
I suspect that it's not a good feature.  It's likely to cause strange, hard to debug interactions with the resource manager and kernel processes.  I don't see a use of the it, and the TPM is specifically designed so that user application would not use it.

Want to do a DoS on the kernel  - just create and save 64 session contexts and everything else is blocked

The resource manager was designed to do all this seamlessly, making each process look like it has exclusive access to the TPM.  It does all the session and object swapping, and making sure the kernel isn't blocked by a user space application.

**Comment by nicowilliams** [comment]
We use the tpm2-tools with the saved context arguments successfully.  I'm not too fond of tpm2-tools; I would prefer to use yours.  The options to use saved contexts make the tpm2-tools CLIs easier to use, though, yes, at the cost of the user not having to be aware of the extra context load/save TPM operations that are then executed automatically.

How can using saved contexts with a resource manager be harder than not using them?  Is it because the RM has heuristics about when it's OK to switch contexts between TPM-using applications?  (Not every Unix has a proper device driver open/close API that could let an RM know when an app is done using the TPM, though nowadays there's no excuse for still not having a proper device driver open/close API.)

> Want to do a DoS on the kernel - just create and save 64 session contexts and everything else is blocked

Yeah, but then you flush them.  That is disruptive to the apps that now have to re-execute potentially complex policies -- one could keep such apps from ever making progress.

I spend a fair bit of time using swtpm w/o an RM and so constantly have to flush key objects, and sometimes sessions too.

> The resource manager was designed to do all this seamlessly, [...]

Right, because the RM does its own context saving and loading as needed.  But certainly if an application wants to load a context, the RM won't prevent it, nor would the RM prevent saving the context.

So one could write applications that use saved contexts as much as possible even though an RM should make that pointless.

Also, saved contexts are an optimization more than they are a user-friendly interface (though they are that too).  One can, for example, create the EK, save it as a saved context, and load it days later, saving the cost of deriving the EK again.  Ditto for any loaded key.  The following example may not be correct, but I suspect that saved contexts can also be used -in some cases- to avoid having to re-execute a complex policy (or having to provide an `authValue`): if loading a duplicated key with `TPM2_Import()` then `TPM2_Load()`, and using the duplication target key object for the import requires authorization, then using a saved context for the loaded key saves the work of satisfying that policy.  Now, one can just save/load contexts manually, but if that can be achieved with command-line options, then there are fewer commands to think about.

From a user perspective, it's very nice to be able to save saved context objects and reuse those as much as possible.  Even for sessions, which can be saved, but not entirely statelessly, it's nice to be able to use saved session contexts in a shell script that uses TPM CLIs.

You can close this issue if you're adamant that context saving and loading has to be explicit in the CLI, but hear me out a bit more.  I recently had an epiphany that the vast majority of the time I just want:

 - a single CLI/API tool that takes
   - a `tpmKey` to use for authenticating the TPM to the application / user,
   - a description of the operation I want to do,
   - including some or all of the key objects that have to be created or [possibly imported then] loaded,
   - and a description of each authorization policy that has to be executed along the way...
   - ...which policies may themselves refer to other key objects that require loading (e.g., a `TPM2_PolicySigned` authorizer's public key), and which might refer to yet other policies (e.g., `TPM2_PolicyAuthorize`, TPM2_PolicyOr`, etc.)
   - and so on recursively
 - any parameters that the described operation (or associated key objects, or policies) might need
 - can prompt for any other parameters not provided explicitly (or which could only be prompted for)
 - then executes the desired operation and all the related operations

I.e., I'd like to generalize the idea of a TPM 2.0 EA policy definition language to a TPM 2.0 usage language.  I want to say "let's `TPM2_Duplicate` to the following `$target` `$some_key` that requires the following policy to be executed [that requires loading some other keys, etc.]".

Such a tool would naturally execute many commands before finally executing the desired command.  Not unlike having a command that requires a key handle _or_ a saved context to load and which then has to do execute than one TPM command, only taking the idea to its limit.

Such a tool would also make it a lot easier to make use of TPM 2.0.  Most of the complexity of TPM 2.0 usage would then move one-time into implementing such a tool, and any number of times into construction of such descriptors, but in the applications themselves it would be very easy to use TPM 2.0: just load the operation descriptor and furnish parameter values / respond to prompts, possibly all in one API call.

**Comment by kgoldman** [comment]
Too much to type in a primitive git text box.  Take it to email if you like.

But basically, the IBM tools work on all OSes and with all RMs, even those that block the context commands.

**Comment by nicowilliams** [comment]
> Too much to type in a primitive git text box. Take it to email if you like.

Heh.  Sometimes I edit in `$EDITOR` then copy-paste into github.  But anyways, I'll close this.

> [...], even those that block the context commands.

Can you tell me more about that?

**Comment by kgoldman** [comment]
I know that the Windows driver blocks context commands.  I assume it's because it would complicate the RM.
