### ISSUE TITLE
 examples to use duplicate and rewrite

### ISSUE THREAD

**Issue by PunyHunter** [kgoldman/ibmtss#8]
Can you provide examples to use duplicate and rewrite, TCG's documentation is difficult to understand, or can you provide some website addresses where there are examples

**Comment by PunyHunter** [comment]
Thank you very much

**Comment by kgoldman** [comment]
See regtests/testdup.sh for several examples of duplicate and rewrap.  I assume you mean rewrap, not rewrite.

My development process is:
- find a test script that's close to my use case
- cut and paste from the script to replicate my use case
- cut and paste C code from the command line programs into my program
For a complicated program, you can replace the script a few lines at a time to help debug

Ask again if something isn't clear.

**Comment by PunyHunter** [comment]
Thanks for your answer.I followed the example(Rewrap) and still couldn't run rewrap and reported some errors.I also don't understand why there are three TPMs. Doesn't "rewrap" only require two TPMs? My background is that there is a KEY under a primary key of TPM1. How to migrate it to a primary key of TPM2? Thank you!

**Comment by kgoldman** [comment]
1. It is important to report what the rewrap error was.  'some errors' is insufficient.

2. Read Part 1 Rewrap to see why it uses three TPMs - the source, the recovery service, and the destination.

3. If you have a key K1 on TPM1 and a storage parent S2 on TPM2, duplicate K1 to S2 public key on TPM1, then import K1 to S2 private key on TPM2.
It does not matter whether the storage parents are primary keys or not.

In the test scripts, see testdup.sh "Duplicate Child Key"
