### ISSUE TITLE
createprimary is hardcoded to use nistp256 for "ST" keys

### ISSUE THREAD

**Issue by chrisfenner** [kgoldman/ibmtss#9]
Could this be a copy-paste error?

https://github.com/kgoldman/ibmtss/blob/8842df895d14acdcd733fe2d4fa0a1305c708594/utils/objecttemplates.c#L267

**Comment by kgoldman** [comment]
It was a bug that I fixed but never pushed to master.  Fixed now.

**Comment by chrisfenner** [comment]
Thanks! Specifically I think f59e5a62e90977a94e57a29d71875a8284d16a53 fixes it.
